# Generated by Django 3.0.7 on 2022-04-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communityboard',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='communityboardimage',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='communitycomment',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='recipeboard',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='recipeboardimage',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='recipecomment',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='recipedata',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='userbookmarkrecipe',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='userrecommendedcommunity',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=20),
        ),
    ]
