# Generated by Django 3.0.7 on 2022-04-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityboard',
            name='header',
            field=models.CharField(choices=[('요리재료게시판', '요리재료게시판'), ('자유게시판', '자유게시판')], max_length=50),
        ),
    ]
