# Generated by Django 3.0.7 on 2022-04-26 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220426_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityboardimage',
            name='boardid',
            field=models.ForeignKey(db_column='boardID', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Communityboard'),
        ),
        migrations.AlterField(
            model_name='communityboardimage',
            name='image',
            field=models.ImageField(null=True, upload_to='communityboard/', verbose_name=''),
        ),
    ]
