# Generated by Django 3.0.7 on 2022-05-04 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220503_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitycomment',
            name='boardid',
            field=models.ForeignKey(db_column='boardID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.Communityboard'),
        ),
        migrations.AlterField(
            model_name='recipecomment',
            name='boardid',
            field=models.ForeignKey(db_column='boardID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.Recipeboard'),
        ),
    ]
