# Generated by Django 3.0.7 on 2022-04-26 04:25

from django.db import migrations, models
import recipeboard.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220426_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeboardimage',
            name='image',
            field=models.ImageField(null=True, upload_to=recipeboard.utils.upload_image, verbose_name=''),
        ),
    ]
