# Generated by Django 3.0.7 on 2022-05-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220427_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ingre',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Userbookmarkrecipe',
        ),
    ]
