# Generated by Django 3.0.7 on 2022-05-03 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipe_data',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.BigIntegerField()),
                ('explan', models.TextField(null=True)),
                ('title', models.CharField(max_length=255)),
                ('ingre', models.TextField()),
                ('amount', models.CharField(max_length=10)),
                ('cook_time', models.CharField(max_length=10)),
                ('level', models.CharField(max_length=20)),
                ('url', models.TextField()),
                ('tag', models.CharField(max_length=20, null=True)),
                ('category_1', models.CharField(max_length=20)),
                ('category_2', models.CharField(max_length=20)),
                ('method', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user_ingre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Userbookmarkrecipe',
            fields=[
                ('bookmarkid', models.IntegerField(primary_key=True, serialize=False)),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('recipeid', models.ForeignKey(blank=True, db_column='recipeid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recipe.recipe_data')),
            ],
            options={
                'db_table': 'userbookmarkrecipe',
                'managed': True,
            },
        ),
    ]
