# Generated by Django 3.0.7 on 2022-04-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipe_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('category_1', models.CharField(max_length=20)),
                ('category_2', models.CharField(max_length=20)),
                ('mgt', models.TextField()),
                ('igd', models.TextField()),
                ('serv', models.CharField(max_length=10)),
                ('cook_time', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='user_ingre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingre', models.TextField()),
            ],
        ),
    ]
