# Generated by Django 3.0.7 on 2022-05-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipe_data',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('explan', models.TextField(null=True)),
                ('num', models.BigIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('ingre', models.TextField()),
                ('amount', models.CharField(max_length=10)),
                ('cook_time', models.CharField(max_length=10)),
                ('level', models.CharField(max_length=20)),
                ('url', models.TextField()),
                ('tag', models.CharField(max_length=20, null=True)),
                ('category_1', models.CharField(max_length=20)),
                ('category_2', models.CharField(max_length=20)),
                ('method', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user_ingre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingre', models.TextField()),
            ],
        ),
    ]
