# Generated by Django 3.0.7 on 2022-05-03 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userbookmarkrecipe',
            fields=[
                ('bookmarkid', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('recipeid', models.ForeignKey(db_column='recipeID', null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe_data')),
                ('userid', models.ForeignKey(db_column='userID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
