# Generated by Django 3.0.7 on 2022-04-18 13:21

from django.db import migrations, models
import django.db.models.deletion
import recipeboard.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Communityboard',
            fields=[
                ('boardid', models.AutoField(db_column='boardID', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=20)),
                ('detail', models.CharField(max_length=5000)),
                ('photo', models.CharField(blank=True, max_length=50, null=True)),
                ('view', models.IntegerField()),
                ('liked', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('location', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'COMMUNITYBOARD',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Recipeboard',
            fields=[
                ('boardid', models.AutoField(db_column='boardID', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('ingredient', models.CharField(max_length=2000)),
                ('detail', models.CharField(max_length=5000)),
                ('view', models.IntegerField()),
                ('recommended', models.IntegerField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'RECIPEBOARD',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Recipedata',
            fields=[
                ('recipeid', models.IntegerField(db_column='recipeID', primary_key=True, serialize=False)),
                ('recipename', models.CharField(max_length=255)),
                ('cookingmethod', models.CharField(max_length=255)),
                ('category_1', models.CharField(max_length=255)),
                ('foodtype', models.CharField(max_length=255)),
                ('category_2', models.CharField(max_length=255)),
                ('detail', models.CharField(max_length=5000)),
                ('ingredient', models.CharField(max_length=5000)),
                ('amount', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'RECIPEDATA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(db_column='userID', primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('allergyinfo', models.CharField(blank=True, max_length=250, null=True)),
                ('notpreferred', models.CharField(blank=True, max_length=250, null=True)),
                ('cookingmethod', models.CharField(blank=True, max_length=250, null=True)),
                ('preferredcategory_1', models.CharField(blank=True, max_length=250, null=True)),
                ('preferredcategory_2', models.CharField(blank=True, max_length=250, null=True)),
                ('cookingtime', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'USER',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Userlike',
            fields=[
                ('likeid', models.AutoField(db_column='bookmarkID', primary_key=True, serialize=False)),
                ('boardid', models.ForeignKey(db_column='boardID', on_delete=django.db.models.deletion.DO_NOTHING, to='recipeboard.Recipeboard')),
                ('userid', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.DO_NOTHING, to='recipeboard.User')),
            ],
            options={
                'db_table': 'USERLIKE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Userbookmark',
            fields=[
                ('bookmarkid', models.AutoField(db_column='bookmarkID', primary_key=True, serialize=False)),
                ('recipeid', models.ForeignKey(db_column='recipeID', on_delete=django.db.models.deletion.DO_NOTHING, to='recipeboard.Recipedata')),
                ('userid', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.DO_NOTHING, to='recipeboard.User')),
            ],
            options={
                'db_table': 'USERBOOKMARK',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Recipephoto',
            fields=[
                ('photoid', models.AutoField(db_column='photoID', primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to=recipeboard.utils.upload_image)),
                ('boardid', models.ForeignKey(db_column='boardID', on_delete=django.db.models.deletion.DO_NOTHING, to='recipeboard.Recipeboard')),
            ],
            options={
                'db_table': 'RECIPEPHOTO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Recipecomment',
            fields=[
                ('commentid', models.AutoField(db_column='commentID', primary_key=True, serialize=False)),
                ('parentcommentid', models.IntegerField(blank=True, db_column='parentcommentID', null=True)),
                ('detail', models.CharField(max_length=500)),
                ('time', models.DateTimeField()),
                ('boardid', models.ForeignKey(db_column='boardID', on_delete=django.db.models.deletion.DO_NOTHING, to='recipeboard.Recipeboard')),
                ('userid', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.DO_NOTHING, to='recipeboard.User')),
            ],
            options={
                'db_table': 'RECIPECOMMENT',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='recipeboard',
            name='userid',
            field=models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.DO_NOTHING, to='recipeboard.User'),
        ),
        migrations.CreateModel(
            name='Communitycomment',
            fields=[
                ('commentid', models.AutoField(db_column='commentID', primary_key=True, serialize=False)),
                ('parentcommentid', models.IntegerField(blank=True, db_column='parentcommentID', null=True)),
                ('detail', models.CharField(max_length=500)),
                ('title', models.DateTimeField()),
                ('boardid', models.ForeignKey(db_column='boardID', on_delete=django.db.models.deletion.DO_NOTHING, to='recipeboard.Communityboard')),
                ('userid', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.DO_NOTHING, to='recipeboard.User')),
            ],
            options={
                'db_table': 'COMMUNITYCOMMENT',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='communityboard',
            name='userid',
            field=models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.DO_NOTHING, to='recipeboard.User'),
        ),
    ]
